config/routes.rb
Rails.application.routes.draw do

  get 'users/update'
  get 'homepage/index'

  get 'homepage/history'
  #get 'homepage/notifications'
  get 'notifications', action: :index, controller: 'notifications'
  post 'homepage/approve_request'

  get 'homepage/about'
  get 'homepage/contact'
  get 'homepage/faq'
  get 'homepage/policy'
  get 'homepage/terms'

  #Profile routes
  # get 'profile', to: 'people#sow'
  # get 'profile/edit', to: 'people#edit'
  # put 'profile', to: 'people#update'
  # get 'profile/new', to: 'people#new'
  resources :people do
    resources :reviews, only:[:index, :new, :create]
  end

  resources :reports
  # , only:[:index, :new, :create, :show, :update]

  #get 'item/index', to: 'item#index'
  #get 'item/show', to: 'item#show'
  #get 'item/update', to: 'item#update'
  #get 'item/edit', to: 'item#edit'

  #TODO: Define the routes to create transactions hierarchically under an item; each transaction .only has one item
  resources :items do
      resources :interactions
  end

  post 'items/request_item'
  post 'items/return_item'

  root 'homepage#index'
  devise_for :users, controllers: {registrations: 'users/registrations',sessions: 'users/sessions'}

  resources :users, only:[:update, :patch]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  # As a note, you can create resources with 'only' to create only some of the routes
  # #resources :people, only: [:edit, :update, :show]
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
    skip_before_action :require_login
    before_action :require_login, only: [:notifications, :history]

    def index

        categories = ['All','Accessories', 'Books', 'Clothing', 'Electronics',
         'Home and Kitchen', 'Luggages and Bags', 'Office Products',
         'Sports and Outdoors', 'Tools and Home Improvement',
         'Toys and Games', 'Other']
        @all_items = Array.new
         if params[:term]
             @all_items = Item.where('name LIKE ?', "%#{params[:term]}%")
             Tag.where('name LIKE ?', "%#{params[:term]}%").each do|tag|
                 @all_items += tag.items.select{|item|!@all_items.include? item}
             end
         else
             @all_items = Item.all
         end

         if params[:category] && params[:category] != ""
             puts "Catergory: " + categories[params[:category].to_i] + " " + params[:category]
             @all_items = @all_items.select{|item|item.category == categories[params[:category].to_i]}
         end

         #remove items that have been reported as stolen
         puts "number of interactions", Interaction.count
         @all_items = @all_items.select{
             |item| item.interactions.last.blank? || !item.interactions.last.failed? }

        if current_user
            if current_user.locked
                render "locked"
            end
        end

         # @five_star_reviews = find_five_star_reviews
         # @five_star_review_users = get_five_star_review_users
    end

    def history
        @person = Person.find_by_user_id(current_user.id)
        @items = @person.items
        @interactions = Interaction.where(item_id: @items.map(&:id)).order(date: :desc)
    end

    ##############################################
    ##############PRIVATE FUNCTIONS###############
    ##############################################
    private
    # def find_five_star_reviews
    #     five_star_reviews = Review.where(rating: 5.0).last(3)
    #     if five_star_reviews.blank?
    #         return nil
    #     else
    #         return five_star_reviews
    #     end
    # end
    #
    # def get_five_star_review_users
    #     five_star_reviews = find_five_star_reviews
    #     reviewers = []
    #     if five_star_reviews.blank?
    #         return nil
    #     else
    #         five_star_reviews.each do |review|
    #             interaction = Interaction.find_by_id(review.interaction_id)
    #             person = Person.find_by_id(interaction.person_id)
    #             reviewers.push(person)
    #         end
    #         return reviewers
    #     end
    # end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/_landing.html.erb
<div class="jumbotron">
    <h1 class="display-4"> LNDR </h1>
    <p class="lead"> What do you want to borrow? </p>
    <hr class="my-4">
    <p> Looking for a way to save money?
        Look no futher than LNDR! </p>
</div>

app/views/homepage/about.html.erb
<%= link_to 'Back', homepage_index_path %>

app/views/homepage/contact.html.erb
<%= link_to 'Back', homepage_index_path %>

app/views/homepage/faq.html.erb
<%= link_to 'Back', homepage_index_path %>

app/views/homepage/history.html.erb
<div class="container-fluid pt-3">
    <h2>Your History</h2>
    <% if @interactions.count > 0 %>
        <div class="card">
          <ul class="list-group list-group-flush">
            <% @interactions.each do |interaction| %>
                <li class="list-group-item">
                    <div class="row">
                        <% interaction_person = Person.find(interaction.person_id) %>
                        <% interaction_item = Item.find(interaction.item_id) %>
                        <div class="col-2">
                            <div class="row justify-content-end">
                                <b><%= interaction.date.localtime.to_formatted_s(:long_ordinal) %>:</b>
                            </div>
                        </div>
                        <div class="col-10">
                            <% if interaction.requested? %>
                                <%= link_to interaction_person.fullname,
                                        person_path(interaction_person) %> has requested to borrow your item <%= link_to interaction_item.name, item_path(interaction_item) %>
                            <% end %>

                            <% if interaction.approved? %>
                                You have approved <%= link_to interaction_person.fullname,
                                        person_path(interaction_person) %> to borrow your item <%= link_to interaction_item.name, item_path(interaction_item) %>
                            <% end %>

                            <% if interaction.returned? %>
                                <%= link_to interaction_person.fullname,
                                        person_path(interaction_person) %> has returned your item <%= link_to interaction_item.name, item_path(interaction_item) %>
                            <% end %>

                            <% if interaction.available? %>
                                successful transaction with <%= link_to interaction_person.fullname,
                                        person_path(interaction_person) %>
                            <% end %>
                        </div>
                    </div>
                </li>
            <% end %>
          </ul>
        </div>
    <% else %>
        <div class="row justify-content-center pt-5">
            <p>Looks like you have no history yet</p>
        </div>
        <div class="row justify-content-center">
            <%= link_to 'Check out some items', homepage_index_path, :class => 'btn btn-blue' %>
        </div>
    <% end %>
</div>

app/views/homepage/index.html.erb
<% if !current_user %>
    <%= render "landing" %>
<% end %>


  <div class="container-fluid mt-4">
    <div class="row justify-content-center">
       <%= form_tag(homepage_index_path, method: :get, :class => "form-inline my-2 my-lg-0") do %>
       <%= select_tag :category, options_for_select([['Accessories', 1], ['Books', 2], ['Clothing', 3],
                                                     ['Electronics', 4], ['Home and Kitchen', 5],
                                                     ['Luggages and Bags', 6], ['Office Products', 7],
                                                     ['Sports and Outdoors', 8], ['Tools and Home Improvement', 9],
                                                     ['Toys and Games', 10],['Other', 11]],  params[:category]),
                      {:include_blank => "All", :class => "form-control mr-sm-2"} %>
        <%= text_field_tag :term, params[:term], :class => "form-control mr-sm-2" %>
         <%= submit_tag 'Search', :class => "btn btn-blue my-2 my-sm-0"%>
       <% end %>
    </div>

    <% if @all_items %>
      <div class="card-columns pt-4">
        <% @all_items.each_with_index do |item, index| %>
          <div class="card border-0 mb-3">
            <img class="card-img-top img-responsive">
              <% if !item.photos.empty? %>
                <%= link_to image_tag(item.photos[0], style:'width:100%',
                                      :class => 'dblock w-100 rounded'), item_path(item) %>
              <% else %>
                <%= link_to image_tag('default_img.png', style:'width:100%',
                                      :class => 'dblock w-100 rounded'), item_path(item) %>
              <% end %>
            </img>
            <div class="card-body">
              <h5 class="card-title">
                <%= "#{item.name}" %>
              </h5>
              <p class="card-text" >
                <% if item.get_item_distance(current_user) %>
                  <%= item.get_item_distance(current_user) %> km away
                <% end %>
              </p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/homepage/locked.html.erb
<div class="container-fluid mt-5">
  <div class="row justify-content-center">
    <div class="col-4">
      <div class="card">
        <div class="card-body">
          <h3>Your account has been locked by a LNDR admin!</h3>
          <h5>Please email admin@lndr.com to resolve the issue.</h5>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homepage/policy.html.erb
<%= link_to 'Back', homepage_index_path %>

app/views/homepage/terms.html.erb
<%= link_to 'Back', homepage_index_path %>