config/routes.rb
Rails.application.routes.draw do

  get 'users/update'
  get 'homepage/index'

  get 'homepage/history'
  #get 'homepage/notifications'
  get 'notifications', action: :index, controller: 'notifications'
  post 'homepage/approve_request'

  get 'homepage/about'
  get 'homepage/contact'
  get 'homepage/faq'
  get 'homepage/policy'
  get 'homepage/terms'

  #Profile routes
  # get 'profile', to: 'people#sow'
  # get 'profile/edit', to: 'people#edit'
  # put 'profile', to: 'people#update'
  # get 'profile/new', to: 'people#new'
  resources :people do
    resources :reviews, only:[:index, :new, :create]
  end

  resources :reports
  # , only:[:index, :new, :create, :show, :update]

  #get 'item/index', to: 'item#index'
  #get 'item/show', to: 'item#show'
  #get 'item/update', to: 'item#update'
  #get 'item/edit', to: 'item#edit'

  #TODO: Define the routes to create transactions hierarchically under an item; each transaction .only has one item
  resources :items do
      resources :interactions
  end

  post 'items/request_item'
  post 'items/return_item'

  root 'homepage#index'
  devise_for :users, controllers: {registrations: 'users/registrations',sessions: 'users/sessions'}

  resources :users, only:[:update, :patch]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  # As a note, you can create resources with 'only' to create only some of the routes
  # #resources :people, only: [:edit, :update, :show]
end

app/models/person.rb
class Person < ApplicationRecord
    belongs_to :user, optional: true
    has_many :items, dependent: :destroy
    has_one_attached :avatar
    has_many :reviews, dependent: :destroy
    has_many :reports, dependent: :destroy

    geocoded_by :address
    after_validation :geocode

    reverse_geocoded_by :latitude, :longitude
    after_validation :reverse_geocode

    validates :fname,:presence => true
    validates :lname, :presence => true
    validates :street,:presence => true
    validates :city, :presence => true
    validates :province,:presence => true
    validates :country, :presence => true

    def address
        [street, city, province, country].compact.join(', ')
    end

    def fullname
        return fname + ' ' + lname
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  skip_before_action :require_login
  skip_before_action :num_of_notifications, only: [:new, :create]

  def new
      @person = Person.new
  end

  def create
      @person = Person.new(people_params)
      @person.user_id = current_user.id
      if @person.save
          redirect_to homepage_index_path
      else
          render 'new'
      end
  end

  def edit
    @person = Person.find_by_user_id(current_user.id);
  end

  def show
    @person = Person.find_by_id(params[:id]);
    @is_current_user = true
    if current_user.id != Person.find_by_id(params[:id]).user_id
        @is_current_user = false
    end
    add_default_image
  end

  def update
    @person = Person.find_by_user_id(current_user.id);
    @person.update(people_params)
    redirect_to person_path
  end

  private
    def people_params
      params.require(:person).permit(:fname, :lname, :street, :city, :province,
                                     :country, :phone, :avatar)
    end

    def add_default_image
      if !@person.avatar.attached?
        @person.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default_avatar.jpg')), filename: 'default_avatar.jpg', content_type: 'image/jpg')
      end
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_error.html.erb
<% if @person.errors.any? %>
    <div id="error_explanation">
      <p>
        <%= pluralize(@person.errors.count, "error") %> prohibited
        this item from being saved:
      </p>
      <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/people/edit.html.erb
<div class="container-fluid mt-5">
  <div class="row justify-content-center">
    <div class="col-sm-5">
      <div class="card">
          <div class="card-body">
            <h1>Edit Profile</h1>
            <%= form_with(model: @person, local: true) do |form| %>
              <div class='form-group'>
                <%= form.label :fname, "First Name" %><br>
                <%= form.text_field :fname, placeholder: @person.fname, :class => "form-control" %>
              </div>

              <div class='form-group'>
                <%= form.label :lname, "Last Name" %><br>
                <%= form.text_field :lname, placeholder: @person.lname, :class => "form-control" %>
              </div>

              <div class='form-group'>
                <%= form.label :street, "Street Address" %><br>
                <%= form.text_field :street, placeholder: @person.street, :class => "form-control" %>
              </div>

              <div class='form-group'>
                <%= form.label :city, "City" %><br>
                <%= form.text_field :city, placeholder: @person.city, :class => "form-control" %>
              </div>

              <div class='form-group'>
                <%= form.label :province, "Province" %><br>
                <%= form.text_field :province, placeholder: @person.province, :class => "form-control" %>
              </div>

              <div class='form-group'>
                <%= form.label :country, "Country" %><br>
                <%= form.text_field :country, placeholder: @person.country, :class => "form-control" %>
              </div>

              <div class="form-group">
                <%= form.label :phone, "Phone Number" %><br>
                <%= form.text_field :phone, placeholder: @person.phone, :class => "form-control" %>
              </div>

              <div class="form-group">
                <%= form.label :avatar, "Profile Picture" %><br>
                <%= form.file_field :avatar, :class => "form-control-file" %>
              </div>

              <div class="row justify-content-center">
                <%= form.submit 'Update', :class => "btn btn-blue" %>
              </div>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/people/new.html.erb
<div class="container-fluid mt-5">
  <div class="row justify-content-center">
    <div class="col-sm-5">
      <div class="card">
          <div class="card-body">
            <h1>Personal Information</h1>
            <%= form_with scope: :person, url: people_path, local: true do |form| %>
              <div class="form-group">
                <%= form.label :fname, "First Name" %><span class="text-error"> *</span>
                <%= form.text_field :fname, :class => "form-control" %>
                <% @person.errors[:fname].each do |msg| %>
                  <small class="form-text text-error">First Name <%= msg %></small>
                <% end %>
              </div>

              <div class="form-group">
                <%= form.label :lname, "Last Name" %><span class="text-error"> *</span>
                <%= form.text_field :lname, :class => "form-control" %>
                <% @person.errors[:lname].each do |msg| %>
                  <small class="form-text text-error">Last Name <%= msg %></small>
                <% end %>
              </div>

              <div class="form-group">
                <%= form.label :street, "Street Address" %><span class="text-error"> *</span>
                <%= form.text_field :street, :class => 'form-control' %>
                <% @person.errors[:street].each do |msg| %>
                  <small class="form-text text-error">Street Adrress <%= msg %></small>
                <% end %>
              </div>

              <div class="form-group">
                <%= form.label :city, "City" %><span class="text-error"> *</span>
                <%= form.text_field :city, :class => 'form-control' %>
                <% @person.errors[:city].each do |msg| %>
                  <small class="form-text text-error">City <%= msg %></small>
                <% end %>
              </div>

              <div class="form-group">
                <%= form.label :province, "Province" %><span class="text-error"> *</span>
                <%= form.text_field :province, :class => "form-control" %>
                <% @person.errors[:province].each do |msg| %>
                  <small class="form-text text-error">Province <%= msg %></small>
                <% end %>
              </div>

              <div class="form-group">
                <%= form.label :country, "Country" %><span class="text-error"> *</span>
                <%= form.text_field :country, :class => "form-control" %>
                <% @person.errors[:country].each do |msg| %>
                  <small class="form-text text-error">Country <%= msg %></small>
                <% end %>
              </div>

              <div class="form-group">
                <%= form.label :phone, "Phone Number" %><br>
                <%= form.text_field :phone, :class => "form-control" %>
              </div>

              <div class="form-group">
                <%= form.label :avatar, "Profile Picture" %><br>
                <%= form.file_field :avatar, :class => "form-control-file" %>
              </div>

              <div class="row justify-content-center">
                <%= form.submit 'Submit', :class => "btn btn-blue" %>
              </div>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/people/show.html.erb
<div class="container-fluid mt-3">
	<div class="row pt-4 justify-content-center">
		<div class="col-sm-4 pl-3 pr-3">
			<div class="card border-0">
            <%= image_tag(@person.avatar, :class => "card-img-top img-responsive rounded img-thumbnail") %>
	        	<div class="card-body">
	        		<div class="row justify-content-center">
	        			<div class="col">
		        			<p>
							  <strong>First Name:</strong>
							  <%= @person.fname %>
							</p>
							<p>
							  <strong>Last Name:</strong>
							  <%= @person.lname %>
							</p>
                            <% if @is_current_user %>
    							<p>
    							  <strong>Street Address:</strong>
    							  <%= @person.street %>
    							</p>
                                <p>
                                  <strong>City:</strong>
                                  <%= @person.city %>
                                </p>
                                <p>
                                  <strong>Province:</strong>
                                  <%= @person.province %>
                                </p>
                                <p>
                                  <strong>Country:</strong>
                                  <%= @person.country %>
                                </p>
                            <% else %>
                                <p>
                                  <strong>Email:</strong>
                                  <%= User.find_by_id(@person.user_id).email %>
                                </p>
                            <% end %>
							<p>
							  <strong>Phone Number:</strong>
							  <%= @person.phone %>
							</p>
                  <p>
                    <strong>Community Rating:</strong>
                    <% rating = @person.rating %>
                    <% if rating %>
                      <%= rating.round(2) %>/5
                    <% else %>
                      <%= "No Ratings Yet" %>
                    <% end %>
                  </p>
						</div>
	        		</div>
                    <% if @is_current_user %>
                        <%= link_to 'Edit Profile', edit_person_path %>
                    <% else %>
                        <%= link_to 'Report This User', new_report_path(person_id: @person.id) %>
                    <% end %>
                    <% if current_user.admin %>
                      <%= link_to 'View Reports', reports_path(person_id: @person.id) %>
                    <% end %>
	        	</div>
	        </div>
		</div>
		<div class="col-sm-4 pl-3">
            <h3>Recent Reviews for <%= @person.fname %></h3>
            <% if @person.reviews.any? %>
              <% reviews = Review.find(@person.review_ids.last(3)) %>
              <% reviews.reverse.each do |review| %>
                    <div class="card border-0">
                      <div class="card-body">
                          <% reviewer = Person.find(review.reviewer) %>
                          <h6>Review by <%= reviewer.fname %> <%= reviewer.lname %>: <%= review.rating %>/5 </h6>
                          <p><%= review.comment %></p>
                      </div>
                    </div>
              <% end %>
              <%= link_to 'See All Reviews', person_reviews_path(person_id: @person.id) %>
            <% end %>
		</div>
	</div>
</div>