config/routes.rb
Rails.application.routes.draw do

  get 'users/update'
  get 'homepage/index'

  get 'homepage/history'
  #get 'homepage/notifications'
  get 'notifications', action: :index, controller: 'notifications'
  post 'homepage/approve_request'

  get 'homepage/about'
  get 'homepage/contact'
  get 'homepage/faq'
  get 'homepage/policy'
  get 'homepage/terms'

  #Profile routes
  # get 'profile', to: 'people#sow'
  # get 'profile/edit', to: 'people#edit'
  # put 'profile', to: 'people#update'
  # get 'profile/new', to: 'people#new'
  resources :people do
    resources :reviews, only:[:index, :new, :create]
  end

  resources :reports
  # , only:[:index, :new, :create, :show, :update]

  #get 'item/index', to: 'item#index'
  #get 'item/show', to: 'item#show'
  #get 'item/update', to: 'item#update'
  #get 'item/edit', to: 'item#edit'

  #TODO: Define the routes to create transactions hierarchically under an item; each transaction .only has one item
  resources :items do
      resources :interactions
  end

  post 'items/request_item'
  post 'items/return_item'

  root 'homepage#index'
  devise_for :users, controllers: {registrations: 'users/registrations',sessions: 'users/sessions'}

  resources :users, only:[:update, :patch]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  # As a note, you can create resources with 'only' to create only some of the routes
  # #resources :people, only: [:edit, :update, :show]
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :person
    has_many :interactions, dependent: :destroy
    has_many_attached :photos
    has_and_belongs_to_many :tags

    validates :name, :presence => true

    def get_item_distance(current_user)
        if current_user.blank?
            return nil
        end
        if current_user
            person = Person.find_by_user_id(current_user.id)
            if person.blank?
                current_user.destroy
                return nil
            end
        end
        cur_person_location = Person.find_by_user_id(current_user.id)
        other_person_location = Person.find_by_id(self.person_id)
        distance = cur_person_location.distance_to(other_person_location, :km)
        if distance.blank?
            return nil
        end

        return distance.round(2)
    end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
    def index
        @show_your_items = params[:your_items]
        if @show_your_items == 'true'
            @user_items = current_user.items
        else
            user_id = current_user.id
            @user_items = Item.where(current_holder: user_id)
        end
    end

    def show
    end

    def update
    end

    def edit
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
        @person = Person.find_by_user_id(current_user.id)
        @show_your_items = params[:your_items]
        @interactions = nil

        if @show_your_items == 'true'
            @user_items = @person.items

        else
            @user_items = Item.where(current_holder: @person.id)

            # For all of current users borrowed items, get the most recent interaction that occurred
            # (should be the 'Approved' interaction)
            logger.debug "number of owned interactions"
            logger.debug @user_items.map(&:id)
            @interactions = Interaction.where(person_id: @person.id,
                                              item_id: @user_items.map(&:id))
                                       .order("created_at DESC")
            # @interactions = @user_items.interactions.where(person_id: @person.id)
            #                                         .order("created_at DESC")
            logger.debug "number of owned interactions"
            logger.debug @interactions.count
        end
    end

    def update
        find_item_and_person
        @item.photos.purge
        if @item.update(item_params)
            populateTagLinks
            redirect_to @item
        else
            render 'edit'
        end
    end

    def edit
        find_item_and_person
    end

    def show
        find_item_and_person
        @valid_interaction = verify_interaction
        @interaction = Interaction.new
        @item_owner  = Person.find_by_id(@item.person_id)
        @item_category = get_item_category(@item)
        @latitude, @longitude = get_item_location(@item_owner)
    end

    def new
        @item = Item.new
    end

    def create
        @person = Person.find_by_user_id(current_user.id)
        @item = @person.items.create(item_params)
        puts params[:tags]
        populateTagLinks
        if @item.errors.any?
            render 'new'
        else
            redirect_to item_path(@item)
        end
    end

    def destroy
        find_item_and_person

        # destroy interactions related to this item
        @interactions = Interaction.where(id: @item.id)
        @interactions.destroy_all

        @item.destroy
        redirect_to items_path
    end


    ##############################################
    ##############PRIVATE FUNCTIONS###############
    ##############################################
    private

    def get_item_category(category)
        if category == "1"
            return "Accessories"
        elsif category == "2"
            return "Books"
        elsif category == "3"
            return "Clothing"
        elsif category == "4"
            return "Electronics"
        elsif category == "5"
            return "Home and Kitchen"
        elsif category == "6"
            return "Luggages and Bags"
        elsif category == "7"
            return "Office Products"
        elsif category == "8"
            return "Sports and Outdoors"
        elsif category == "9"
            return "Tools and Home Improvement"
        elsif category == "10"
            return "Toys and Games"
        elsif category == "11"
            return "Other"
        else
            return "None"
        end
    end

    def find_item_and_person
        @person = Person.find_by_user_id(current_user.id)
        @item = Item.find(params[:id])
    end

    def find_most_recent_approved_interaction
        interaction_with_item = Interaction.where(item_id: @item.id).order("date")
        interaction_with_item_approved = interaction_with_item.where(status: :approved)
        last_approved_interaction = interaction_with_item_approved.last
        return last_approved_interaction
    end

    def find_most_recent_available
        interaction_with_item = Interaction.where(item_id: @item.id).order("date")
        interaction_with_item_returned = interaction_with_item.where(status: :available)
        if interaction_with_item_returned.count > 0
            last_returned_date = interaction_with_item_returned.last.date
            return last_returned_date
        else
            return nil
        end
    end

    def is_a_double_request(requested_interactions)
        #puts "requested interactions:", requested_interactions.all
        if requested_interactions.where(person_id: @person.id, status: :requested).count > 0
			return false
		else
			return true
		end
    end

    def verify_interaction
        #if it is the owner, she/he cannot request the item
        if @person.items.include?(@item)
        	return false
        else
            #in this case you are a borrower requesting an item
            #puts "number of interactions: ", Interaction.all.count, @item.id, Interaction.where(item_id: @item.id).start_date
            # Interaction.all.each do |i|
            #     puts "item_id: ", i.item_id
            # end
            interaction_with_item = Interaction.where(item_id: @item.id).order("date")
            if interaction_with_item.count > 0
                cur_item = interaction_with_item.last
                #if the item is avaiable again, anyone can borrow the item again
                if cur_item.available?
                    puts "-----------item is returned"
                    return true
                #no one can request an item once it has been borrowed
                elsif cur_item.approved?
                    puts "-----------item was approved"
                    return false

                elsif cur_item.returned?
                    puts "-----------item was approved"
                    return false
                #if the item is currently being requested, then you are only allowed
                #one request per time the item is out
                elsif cur_item.requested?
                    puts "-----------the item is requested"
                    last_returned_date = find_most_recent_available
                    if last_returned_date != nil
                        interactions_after_last_returned_date = interaction_with_item.where("date > ?", last_returned_date)
                        return is_a_double_request(interactions_after_last_returned_date)
                    else
                        puts "-----------not ever returned"
                        return is_a_double_request(interaction_with_item)
                    end
                else
                    puts "something is fucked!"
                end
            else
                puts "-----no valid interactions"
                return true
            end
        end
    end

    def item_params
        category = params[:item][:category]
        params[:item][:category] = get_item_category(category)
        params.require(:item).permit(:name, :description, :start_date, :end_date, :category, photos: [])
    end

    def populateTagLinks
      @item.tags.clear
      tagsList = params[:tags].split(/[\n ,]+/).map(&:strip) #split by commas and remove whitespaces
      tagsList.each do |item|
          curTag = Tag.find_by_name(item)
          if curTag == nil
              curTag = Tag.create(name: item)
          end
          @item.tags << curTag
      end
    end

    def get_item_location(item_owner)
        # if current_user.blank?
        #     return nil
        # end
        # cur_person = Person.find_by_id(@item.person_id)

        return item_owner.latitude, item_owner.longitude
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item, local: true do |form| %>
  <div class='form-group'>
    <%= form.label :name %><br>
    <%= form.text_field :name, :class => 'form-control' %>
    <% if @item.errors.any? %>
      <% if @item.errors[:name] %>
        <% @item.errors[:name].each do |msg| %>
          <small class="form-text text-error">Name <%= msg %></small>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class='form-group'>
    <%= form.label :description %><br>
    <%= form.text_area :description, :class => 'form-control', :row => '3' %>
  </div>

  <div class='form-group'>
    <%= form.label :category %><br>
    <%= form.select :category, [['Accessories', 1], ['Books', 2], ['Clothing', 3], ['Electronics', 4],
                                ['Home and Kitchen', 5], ['Luggages and Bags', 6], ['Office Products', 7],
                                ['Sports and Outdoors', 8], ['Tools and Home Improvement', 9],
                                ['Toys and Games', 10],['Other', 11]], {}, {:class => 'form-control'} %>
  </div>

  <div class='form-group'>
    <%= form.label :photos %><br>
    <%= form.file_field :photos, multiple: true, :class => 'form-control-file'%>
  </div>

  <div class='form-group'>
    <%= form.label :tags %><br>
    <%= text_area_tag :tags, @item.tags.map{|tag| tag.name}.join(" "), :class => 'form-control', :row => '3' %>
  </div>

  <div class="row justify-content-center">
    <%= form.submit 'Submit', :class => 'btn btn-blue'%>
  </div>

<% end %>

app/views/items/edit.html.erb
<div class='container-fluid mt-5'>
	<div class='row justify-content-center'>
		<div class='col-sm-4'>
			<div class="card">
		        <div class="card-body">
					<h1></h1>
					<h1>Edit Item</h1>
				  	<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/items/index.html.erb
<%# Idea: maybe have the index page with no url params, and just display both your items and borrowed items
    simultaneously %>

<div class="container-fluid mt-3">
  <% if @show_your_items == 'true' %>
    <h1> Your Items: </h1>
  <% else %>
    <h1> Your Borrowed Items: </h1>
  <% end %>

  <div class="row">
    <% if @user_items %>
        <% @user_items.each_with_index do |item, index| %>
            <div class="col-sm-2">
                <div class="card border-0">
                    <img class="card-img-top img-responsive">
                        <% if !item.photos.empty? %>
                            <%= link_to image_tag(item.photos[0], style:'width:100%',
                                :class => "dblock w-100 rounded"), item_path(item) %>
                        <% else %>
                            <%= link_to image_tag('default_img.png', style:'width:100%',
                                :class => "dblock w-100 rounded"), item_path(item) %>
                        <% end %>
                    </img>
                    <div class="card-body">
                        <%= "#{item.name}" %>
                        <% if @show_your_items == 'false' and !@interactions.nil? %>
                            <br>
                            <%= link_to_if (@interactions[index].approved?),
                            'Return Item',
                            {controller: :interactions,
                             action: :create,
                             item_id: @interactions[index].item_id,
                             interaction: {
                                request_type: 2,
                                start_date: @interactions[index].start_date,
                                end_date: @interactions[index].end_date,
                                person_id: @interactions[index].person_id}}, method: :post %>
                            <br>
                            by
                            <%= "#{@interactions[index].end_date}" %>
                        <% end %>
                        <% if !item.current_holder.blank? and @show_your_items == 'true' %>
                            <br>
                            lent item to
                            <%  borrower = Person.find_by_id(item.current_holder) %>
                            <%= link_to "#{borrower.fname} #{borrower.lname}", person_path(borrower) %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="container-fluid mt-5">
	<div class="row justify-content-center">
		<div class="col-sm-4">
			<div class="card">
	        	<div class="card-body">
					<h1></h1>
					<h1>New Item</h1>
				  	<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/items/show.html.erb
<div class='container-fluid'>
  <div class='row justify-content-center'>
    <div class ='col-sm-4 mt-4'>
      <% if !@item.photos.empty? %>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <% @item.photos.each_with_index do |photo, i| %>
              <% if i == 0 %>
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <% else %>
                <li data-target="#carouselExampleIndicators" data-slide-to=<%= i.to_s %>></li>
              <% end %>
            <% end %>
          </ol>
          <div class="carousel-inner carousel-image-container rounded">
            <% @item.photos.each_with_index do |photo, i| %>
              <% if i == 0 %>
                <div class="carousel-item active">
                  <%= image_tag(photo, style:'width:100%', :class => 'item-responsive') %>
                </div>
              <% else %>
                <div class="carousel-item">
                  <%= image_tag(photo, style:'width:100%', :class => 'item-responsive') %>
                </div>
              <% end %>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% else %>
        <%= image_tag('default_img.png', style:'width:100%', :class => 'item-responsive rounded') %>
      <% end %>
    </div>

    <div class='col-sm-4 mt-4'>
      <% if @interaction.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@interaction.errors.count, "error") %> prohibited
            this item from being saved:
          </h2>
          <ul>
            <% @interaction.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <h1><%= @item.name %></h1>

      <h3>Lender</h3>
      <% if @item_owner.blank? %>
        <% @item_owner = Person.find_by_id(@item.person_id) %>
      <% end %>
      <p><%= link_to @item_owner.fname, person_path(@item_owner) %></p>

      <h3>Description</h3>
      <p><%= @item.description %></p>

      <h3>Category</h3>
      <p><%= @item.category %></p>

      <h3>Tags</h3>
      <p>
        <% @item.tags.each do |tag| %>
          <%= link_to ('#' + tag.name), homepage_index_path(:term => tag.name) %>
        <% end %>
      </p>

      <h3>Location</h3>
      <% if ( @latitude.blank? || @longitude.blank? ) %>
        <% @latitude = @item_owner.latitude %>
        <% @longitude = @item_owner.longitude %>
      <% end %>
      <%= image_tag "https://api.mapbox.com/styles/v1/mapbox/streets-v10/static/#{@longitude},#{@latitude},15/400x150?access_token=pk.eyJ1IjoiaGV5aXRzcmlzYWFhYSIsImEiOiJjam96eTRqMWswMnI0M3FwaTMyZW9zbjJsIn0.5a2PnnqR8pKh1MaG3A6uxQ",
          :class => "img-fluid rounded" %><br>

      <% if @valid_interaction %>
          <h3>Borrow Item</h3>
          <%= form_with(model: [@item, @item.interactions.build], local: true) do |form| %>
              <div class="form-group" >
                <%= form.label :start_date %><br>
                <%= form.date_field :start_date, :class => 'form-control' %>
              </div>

              <div class="form-group" >
                <%= form.label :end_date %><br>
                <%= form.date_field :end_date, :class => 'form-control' %>
              </div>

              <%= form.hidden_field :request_type, :value => 0 %>

              <div class="row justify-content-center">
                <%= form.submit 'Request Item', :class => 'btn btn-blue'%>
              </div>
          <% end %>
      <% end %>
      <% if @person.items.include?(@item) %>
        <%= link_to 'Edit Item', edit_item_path(@item) %> |
        <%= link_to 'Remove Item', [@item],
                     method: :delete,
                     data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
</div>